spring.application.name=online_shopping_backend
# Database configuration (Replace with your configuration)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=none
# Database table names and column names are case-sensitive.
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.messages.basename=messages
# Don't initialize the database with SQL scripts
spring.sql.init.mode=never
#logging.level.org.springframework.web=DEBUG

spring.mvc.pathmatch.matching-strategy=ant_path_matcher